version: '3'

services:
  db:
    image: libreosteo-pg
    hostname: pg_1
    volumes:
      - ${LIBREOSTEO_DB_STORAGE}:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - ${LIBREOSTEO_BAK_STORAGE}:/var/lib/backup
    environment:
      - POSTGRES_USER=libreosteo
      - POSTGRES_PASSWORD=libreosteo
      - POSTGRES_DB=libreosteo
  libreosteo:
    image: libreosteo-http
    hostname: libreosteo_1
    ports:
      - "8085:8085"
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}:/Libreosteo/data
      - ${SETTINGS}:/Libreosteo/settings
